/**
 * mailbox-sim.ts — the LOCAL MAILBOX SIMULATOR behind the storyboard
 * walk's Gmail-shaped connector.
 *
 * Honesty contract (the walk's hard core): this is a simulator and is
 * LABELED as one everywhere it surfaces. What is NOT simulated are the
 * observations made of it — every reliability/latency posterior the
 * walk vends is measured from real local calls into this class doing
 * real work (scans over the fixture corpus). The numbers honestly
 * describe the simulator; nothing pretends they describe Gmail.
 *
 * Deterministic by construction: the fixture corpus is generated by a
 * fixed formula (no randomness, no wall-clock content), so every walk
 * on every machine holds the same 24 messages.
 */

export type SimMessage = {
  id: string;
  from: string;
  to: string;
  subject: string;
  body: string;
  /** Fixture timestamp (ms) — synthetic epoch, not wall clock. */
  ts: number;
  labels: string[];
};

const SENDERS = ['ana@example.test', 'bo@example.test', 'cy@example.test', 'di@example.test'];
const TOPICS = ['invoice', 'standup', 'release', 'onboarding', 'renewal', 'retro'];
const LABELSETS = [['inbox'], ['inbox', 'starred'], ['archive'], ['inbox', 'billing']];

export function fixtureCorpus(owner: string): SimMessage[] {
  const out: SimMessage[] = [];
  for (let i = 0; i < 24; i++) {
    const topic = TOPICS[i % TOPICS.length];
    out.push({
      id: `m${String(i + 1).padStart(3, '0')}`,
      from: SENDERS[i % SENDERS.length],
      to: owner,
      subject: `${topic} #${Math.floor(i / TOPICS.length) + 1}`,
      body: `Message ${i + 1} about the ${topic}. Please review when you can. ` +
        `Thread token ${topic}-${(i * 7) % 100}.`,
      ts: 1_750_000_000_000 + i * 3_600_000,
      labels: LABELSETS[i % LABELSETS.length],
    });
  }
  return out;
}

export class MailboxSim {
  private readonly corpus: SimMessage[];
  private readonly apiKey: string;
  /** Messages "sent" through the simulator — exists so the kit's verb
   *  EXCLUSION has something real to refuse. */
  readonly outbox: SimMessage[] = [];

  /** The sim plays the REMOTE SERVICE, so IT holds the credential
   *  truth: every api verifies the caller's key, exactly like the
   *  provider a real connector would talk to. */
  constructor(owner: string, apiKey: string) {
    this.corpus = fixtureCorpus(owner);
    this.apiKey = apiKey;
  }

  private verify(auth: string | undefined): void {
    if (auth !== this.apiKey) throw new Error('unauthorized (simulator): missing or invalid key');
  }

  /** Full-scan search over subject+body — real work, really measured. */
  search(q: string, auth?: string): { ids: string[] } {
    this.verify(auth);
    const needle = q.toLowerCase();
    const ids: string[] = [];
    for (const m of this.corpus) {
      if (m.subject.toLowerCase().includes(needle) || m.body.toLowerCase().includes(needle)) {
        ids.push(m.id);
      }
    }
    return { ids };
  }

  get(id: string, auth?: string): { from: string; subject: string; body: string; labels: string } {
    this.verify(auth);
    const m = this.corpus.find((x) => x.id === id);
    if (!m) throw new Error(`no message '${id}'`);
    return { from: m.from, subject: m.subject, body: m.body, labels: m.labels.join(',') };
  }

  labels(auth?: string): { labels: string } {
    this.verify(auth);
    const all = new Set<string>();
    for (const m of this.corpus) for (const l of m.labels) all.add(l);
    return { labels: [...all].sort().join(',') };
  }

  send(to: string, subject: string, body: string, auth?: string): { ok: boolean } {
    this.verify(auth);
    this.outbox.push({
      id: `out${this.outbox.length + 1}`, from: 'me', to, subject, body, ts: 0, labels: ['sent'],
    });
    return { ok: true };
  }
}
